const char* HTML_CONTENT = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"UTF-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"    <title>Plant Monitoring System</title>\n"
"    <style>\n"
"      body {\n"
"        font-family: 'Segoe UI', sans-serif;\n"
"        background-color: #e8f5e9;\n"
"        color: #2e7d32;\n"
"        margin: 0;\n"
"        padding: 20px;\n"
"        display: flex;\n"
"        justify-content: center;\n"
"        align-items: center;\n"
"        min-height: 100vh;\n"
"      }\n"
"      .container {\n"
"        background: #ffffff;\n"
"        padding: 20px;\n"
"        border-radius: 16px;\n"
"        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\n"
"        max-width: 400px;\n"
"        width: 100%;\n"
"      }\n"
"      h1 {\n"
"        text-align: center;\n"
"        color: #1b5e20;\n"
"        margin-bottom: 20px;\n"
"      }\n"
"      .stat {\n"
"        background-color: #f1f8e9;\n"
"        border: 2px solid #c8e6c9;\n"
"        border-radius: 12px;\n"
"        padding: 16px;\n"
"        margin-bottom: 15px;\n"
"        text-align: center;\n"
"      }\n"
"      .stat .label {\n"
"        display: block;\n"
"        font-weight: bold;\n"
"        font-size: 1.1em;\n"
"        margin-bottom: 5px;\n"
"        color: #388e3c;\n"
"      }\n"
"      .stat span.value {\n"
"        font-size: 1.4em;\n"
"        font-weight: 600;\n"
"      }\n"
"      button {\n"
"        padding: 10px 20px;\n"
"        font-size: 1em;\n"
"        background-color: #66bb6a;\n"
"        border: none;\n"
"        border-radius: 8px;\n"
"        color: white;\n"
"        cursor: pointer;\n"
"      }\n"
"      @media (max-width: 480px) {\n"
"        .container {\n"
"          padding: 15px;\n"
"        }\n"
"        .stat {\n"
"          padding: 12px;\n"
"        }\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"container\">\n"
"      <h1>🌱 Plant Monitor</h1>\n"
"      <div class=\"stat\">\n"
"        <span class=\"label\">🌡️ Temperature</span>\n"
"        <span class=\"value\" id=\"temp\">{{TEMP}}</span>\n"
"      </div>\n"
"      <div class=\"stat\">\n"
"        <span class=\"label\">💧 Humidity</span>\n"
"        <span class=\"value\" id=\"humidity\">{{HUMIDITY}}</span>\n"
"      </div>\n"
"      <div class=\"stat\">\n"
"        <span class=\"label\">🌾 Soil Moisture</span>\n"
"        <span class=\"value\" id=\"soil\">{{SOIL}}</span>\n"
"      </div>\n"
"      <div class=\"stat\">\n"
"        <span class=\"label\">📋 Status</span>\n"
"        <span class=\"value\" id=\"status\">{{STATUS}}</span>\n"
"      </div>\n"
"      <div class=\"stat\">\n"
"        <button id=\"waterButton\" onclick=\"waterPlant()\">\n"
"          {{BUTTON_LABEL}}\n"
"        </button>\n"
"      </div>\n"
"    </div>\n"
"\n"
"      <script>\n"
"        function updateData() {\n"
// "          console.log('Updating data...'); // Debug log\n"
"          fetch('/data')\n"
"            .then(res => res.json())\n"
"            .then(data => {\n"
// "              console.log('Data received:', data); // Debug log\n"
"              document.getElementById('temp').innerText = data.temperature;\n"
"              document.getElementById('humidity').innerText = data.humidity;\n"
"              document.getElementById('soil').innerText = data.soil;\n"
"              document.getElementById('status').innerText = data.status;\n"
"            })\n"
"            .catch(err => console.error('Update failed:', err));\n"
"        }\n"
"\n"
"        function waterPlant() {\n"
"          fetch('/water')\n"
"            .then(res => res.json())\n"
"            .then(data => {\n"
"              // Update the button text based on the server's response\n"
"              document.getElementById('waterButton').innerText = data.buttonLabel;\n"
"            })\n"
"            .catch(err => {\n"
"              console.error('Failed to water:', err);\n"
"              alert('Failed to water: ' + err);\n"
"            });\n"
"        }\n"
"\n"
"        window.onload = function() {\n"
"          console.log('Page loaded'); // Debug log\n"
"          updateData();\n"
"          setInterval(updateData, 5000); // Update every 5 seconds\n"
"        };\n"
"      </script>\n"
"  </body>\n"
"</html>\n";
